### ISSUE TITLE
[Redis- 6]: info() function with section 'modules' returns incomplete result.

### ISSUE THREAD

**Issue by Arushi201296** [andymccurdy/redis-py#1392] opened 2020-09-01 14:28 UTC
**Version**: 
redis-py : 3.4.1
redis : 6.0.5

**Platform**: 
Python 3.6.8 on Ubuntu 18.04.5 LTS

**Description**: 
The redis database has two modules - ReJSON and RedisGraph.

CLI lists correct number of modules:
![redis-6-cli](https://user-images.githubusercontent.com/48902477/91863701-05331880-ec8d-11ea-8001-2ceb908d3b5b.png)

When `connection_object.info(section='modules')` is executed , the result seems to be incomplete as only one module is listed in the output. However, `connection_object.execute_command('INFO MODULES')` returns the correct output.
![redis-6-strange](https://user-images.githubusercontent.com/48902477/91863955-4d523b00-ec8d-11ea-959e-c0b986b4695e.png)

**Comment by 2014BDuck** [comment] 2020-09-02 06:10
info[key] = get_value(value)

key, value = line.split(:)

so we got same key for two module line.

Trying to fix it now.

**Comment by RoeyPrat** [comment] 2020-09-02 07:35
Thanks @Arushi201296 !
This looks to me like a duplicate of issue https://github.com/andymccurdy/redis-py/issues/1390.
I'm closing this as duplicate, but please let me know if I'm wrong and it's not.
@2014BDuck I'm assigning you the other issue. let me know if you need help, or would like me to take over that one.

**Closed by RoeyPrat** 2020-09-02 07:35 UTC
