### ISSUE TITLE
Version 3.0.0 and 3.0.1 are broken and had to go back to 2.10.6

### ISSUE THREAD

**Issue by robvdl** [andymccurdy/redis-py#1099] opened 2018-12-05 22:31 UTC
Could be something to do with Celery or Kombu, but as soon as redis-py 3.x was released our app started playing up, we had to go back to the 2.10.6 version. Here is a traceback with celery-py 3.0.1:

```python
Traceback (most recent call last):
  File "/usr/share/appname/venv/lib/python3.4/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/share/appname/venv/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/share/appname/venv/lib/python3.4/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/share/appname/venv/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 316, in start
    blueprint.start(self)
  File "/usr/share/appname/venv/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/share/appname/venv/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 592, in start
    c.loop(*c.loop_args())
  File "/usr/share/appname/venv/lib/python3.4/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/share/appname/venv/lib/python3.4/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/share/appname/venv/lib/python3.4/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/share/appname/venv/lib/python3.4/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/usr/share/appname/venv/lib/python3.4/site-packages/kombu/transport/redis.py", line 724, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/usr/share/appname/venv/lib/python3.4/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
    callback(message)
  File "/usr/share/appname/venv/lib/python3.4/site-packages/kombu/transport/virtual/base.py", line 632, in _callback
    self.qos.append(message, message.delivery_tag)
  File "/usr/share/appname/venv/lib/python3.4/site-packages/kombu/transport/redis.py", line 149, in append
    pipe.zadd(self.unacked_index_key, time(), delivery_tag) \
  File "/usr/share/appname/venv/lib/python3.4/site-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/usr/share/appname/venv/lib/python3.4/site-packages/redis/_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'float' object has no attribute 'items'
```

**Comment by andymccurdy** [comment] 2018-12-05 22:39
Dupe of #1068

Kombu (celery) already authored a fix.

**Closed by andymccurdy** 2018-12-05 22:39 UTC
