### ISSUE TITLE
StrictRedis blocked if socket_timeout=None

### ISSUE THREAD

**Issue by rebornfxx** [andymccurdy/redis-py#1093] opened 2018-12-03 10:13 UTC
I've create a redis client:redis.StrictRedis(
            host=redis_ip, port=redis_port, db=redis_no, password=passwd)

**Comment by andymccurdy** [comment] 2018-12-03 19:15
Dupe of #1094. Closing.

**Closed by andymccurdy** 2018-12-03 19:15 UTC
