### ISSUE TITLE
redis exceptions Connection Error: Connection closed by server

### ISSUE THREAD

**Issue by Alexander770** [andymccurdy/redis-py#1445] opened 2021-01-14 07:56 UTC
Redis config file:
[redis_conf.txt](https://github.com/andymccurdy/redis-py/files/5813031/redis_conf.txt)

Here is an exception:
![exception](https://user-images.githubusercontent.com/53492569/104559735-817f3480-564d-11eb-8088-1ead99210295.JPG)

I run latest version of redis in container:

redis:
      image: redis:latest
      container_name: redis
      ports:
          - 6379:6379
      volumes:
          - ./config/redis.conf:/redis.conf
      command: [ "redis-server", "/redis.conf" ]

The application is written in Python ver 3.9

`import redis

pool = redis.ConnectionPool(host='localhost', port=6379, db=0)
r = redis.Redis(connection_pool=pool)

r.set('foo', 'bar')
value = r.get('foo')
print(value)`

As you see it is very basic. I had more complicated code that I tried to run at the beginning where I communicated with redis in multithread. Later this code caused a problem so that I am not able even to start with the above simple code no matter what I do: restart the computer, restart container, reinstall redis module. nothing helps
I send commands in redis cli and it works. But python throws an exception:

Please help me stay with redis!

**Comment by andymccurdy** [comment] 2021-01-14 19:34
I don't see anything wrong with the code that you posted. Does running `redis-cli` from the host machine (or from the same container that python is run from) successfully connect to the Redis server?

**Comment by Alexander770** [comment] 2021-01-16 18:20
Thanks Andy

I don't have any problem to send commands through redis cli when I am on
container. The problem is with connection. I remember that the issue is
started after some windows update. I just do not know what to do now. The
instability is not good for this kind of application. The functionality
redis gives is exactly what I am looking for but I do not know how to get
around it. What would you suggest? How stable is py redis?

Regards
Alexander

**Comment by andymccurdy** [comment] 2021-01-16 20:36
Is redis-py running on the host OS or within another another container? Have you tried connecting to the server via redis-cli from the same host/container that redis-py is running in?

I'm very confident this is not a redis-py issue. I strongly suspect this is an issue with the networking in docker between the Redis server container and the container running Python or the host OS running Python.

**Comment by Alexander770** [comment] 2021-01-16 21:16
Redis is running in container and I am able to connect to cli on the
container I just cannot reach it from python running on the host. I'll try
to reinstall docker maybe this is the issue.
The actual application is multi processing where each process run few
thousand of threads and each thread connects to redis catch the data make
some processing and puts it back to redis. What would be the best
experience tondo it? I thought to initiate a pool in the parent process
than to pass a client to each thread to make connection to redis. What is
your opinion?

**Comment by andymccurdy** [comment] 2021-01-16 21:37
Try connecting to the Redis server from a `redis-cli` process running outside the Redis container. Again, this sounds like a docker networking issue.

I'd suggest each worker get its own connection pool/client instance.

**Comment by Alexander770** [comment] 2021-01-16 22:02
Each worker you mean each process?

**Comment by andymccurdy** [comment] 2021-01-16 22:11
Yes, each process.

**Comment by Alexander770** [comment] 2021-01-16 22:14
Would it be a good practice if I open connection pool in a process and than
pass it to child threads and each  child thread will make client connection
instance?

**Comment by andymccurdy** [comment] 2021-01-16 22:15
That should be fine. Connection Pools are threadsafe.

**Comment by Alexander770** [comment] 2021-01-17 15:23
Today I reinstalled everything, docker, images rerun containers, nothing
worked.
Got same error: redis.exceptions.ConnectionError: Connection closed by
server.

Maybe there are some relevant settings in redis.conf file like time out
etc?

**Comment by andymccurdy** [comment] 2021-01-17 19:10
The default redis.conf values should "just work". This continues to seem like a docker networking issue. Your next step should be to get *any* client (redis-cli, redis-py, etc.) that is outside of the Redis container connecting to the Redis server process inside the container.

**Comment by Alexander770** [comment] 2021-01-17 20:18
Thanks Andy. Appreciate very much the time you spend to answer me.
I think I pinpointed the problem. When I enter CLI and write* redis-server
../redis.conf* here is what I get:
*Could not create server TCP listening socket 127.0.0.1:6379
<http://127.0.0.1:6379/>: bind: Address already in use*
When I check the port with, *netstat -aon | findstr 6379* , the port is
free. I reinstalled docker, reloaded image, restarted container, nothing
helps.
Can it be that port occupied by some connection request that was not closed
properly in previous sessions? Is there a global reset?

**Comment by Alienmaster** [comment] 2021-01-18 14:31
I have the same issue with two virtual machines. I run various skripts on both machines using redis and the only connection that throws this error (quite often) is the one reading binary data from the redis database.

**Comment by Alexander770** [comment] 2021-01-18 16:41
I found the problem and it made me embarrassed.  The bind IP
connection definition was wrong, redis was bound to IP of local host
instead of container IP.  The second I changed it code started running
properly.

**Comment by andymccurdy** [comment] 2021-01-19 22:26
@Alexander770 Great, glad you figured out what was going on.

@Alienmaster It seems like the issue you're seeing is different than this one, even if you are getting a similar error. Feel free to open a new issue with details on your environment, the error that you're getting and ideally a reproduce-able example.

Closing this issue as it seems to be resolved.

**Closed by andymccurdy** 2021-01-19 22:26 UTC

**Comment by devnm21** [comment] 2022-03-14 11:26
> I found the problem and it made me embarrassed. The bind IP connection definition was wrong, redis was bound to IP of local host instead of container IP. The second I changed it code started running properly.
> […](#)


Hey @Alexander770 , I'm facing the same issue (I think), can you share the conf file you used?

**Comment by Leedeokmu** [comment] 2023-01-27 18:43
@devnm21 can you set 'protected-mode' to 'no' in redis.conf?

**Comment by CrimsonGlory** [comment] 2023-03-07 18:53
For those from google, maybe ```--tls``` flag is missing from your connection url string.
