### ISSUE TITLE
Sporadic "Connection not ready" exceptions with BlockingConnectionPool since 3.2.0

### ISSUE THREAD

**Issue by NirBenor** [andymccurdy/redis-py#1136] opened 2019-02-19 08:53 UTC
**Version:** 
3.2.0

**Platform:**
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
CentOS Linux release 7.5.1804 (Core) on docker

The redis server is using the official docker image.
Redis server v=4.0.11 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=74253224a862200c

**Description:**
Since upgrading to 3.2.0, we started getting sporadic errors in getting connections.
[image](https://user-images.githubusercontent.com/16517192/52999682-1a3fb200-342f-11e9-9a06-3c74feb7ed6d.png)

The code that is running looks like this:
```
    pool = BlockingConnectionPool(max_connections=config.REDIS_CONNECTIONS_PER_WORKER, host=config.REDIS_HOST,  port=config.REDIS_PORT, db=0, timeout=config.REDIS_TIMEOUT)
   redis = StrictRedis(connection_pool=pool)
   redis.setex(...) / redis.get(...)
```

**Additional information:**
This code is running inside an eventlet gunicorn worker.
The server is very "network heavy" and opens lots of sockets (for example, dns queries).
```
127.0.0.1:6379> config get maxclients
1) "maxclients"
2) "10000"
127.0.0.1:6379> info clients
# Clients
connected_clients:104
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
```

**Comment by andymccurdy** [comment] 2019-02-19 15:43
Do you have a traceback by chance?

How often is this happening?

**Comment by andymccurdy** [comment] 2019-02-19 17:52
Also, what version of redis-py did you upgrade from? I assume you weren't seeing errors in that version?

**Comment by NirBenor** [comment] 2019-02-20 09:00
This does not occur in 3.1.0 (we reverted to that and we no longer get these errors).
How often is about 2 exceptions/minute (can be seen in the first image), and we send about 1-2K commands/minute (a graph of "cache misses" only can be seen in the second image). Each bar in the graphs represents 20 minutes.
![image](https://user-images.githubusercontent.com/16517192/53078512-0a8e9f00-34fd-11e9-8c12-0f7cd6307c46.png)
![image](https://user-images.githubusercontent.com/16517192/53078828-bcc66680-34fd-11e9-9275-e673154c1084.png)

The attached image in the issue contains a traceback from `Sentry`.
Here is a text version of a traceback:
```
[2019-02-18 09:18:57.161794] ERROR: hydrogen.app: An unexpected error has occurred on: 172.18.0.2 POST http /enrich/bulk?
Traceback (most recent call last):
  File "/opt/hydrogen/hydrogen/app.py", line 196, in enrich_bulk
    enriched_data = _enrich_bulk(dispatcher, bulk_data, use_mirror, metadata)
  File "/opt/hydrogen/hydrogen/app.py", line 117, in _enrich_bulk
    use_mirror=use_mirror, metadata=metadata)
  File "/opt/hydrogen/hydrogen/core/dispatcher.py", line 99, in enrich
    enrichment_data = enricher.enrich(data_type=data_type, value=value, use_mirror=use_mirror)
  File "/opt/hydrogen/hydrogen/core/enrichers/<>.py", line 55, in enrich
    cached_<> = self.redis.get(<>)
  File "/opt/conda/envs/hydrogen/lib/python3.6/site-packages/redis/client.py", line 1264, in get
    return self.execute_command('GET', name)
  File "/opt/conda/envs/hydrogen/lib/python3.6/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/opt/conda/envs/hydrogen/lib/python3.6/site-packages/redis/connection.py", line 1151, in get_connection
    raise ConnectionError('Connection not ready')
redis.exceptions.ConnectionError: Connection not ready
```

**Comment by andymccurdy** [comment] 2019-02-20 09:20
Interesting. Do you happen to know if eventlet is patching the `select` module? Do you have `select.poll` available in your environment?

Would it be possible for you to run the following snippet in your environment (with eventlet activated)?

```python
from redis.selector import has_selector
has_selector('poll')
```

This way we'll know whether redis-py is using `select.select` or `select.poll` to determine the healthiness of the socket.

**Comment by NirBenor** [comment] 2019-02-20 09:37
Yes, `eventlet` does patch the `select` module.
I followed their `monkey_patch` code, and it appears that in the bottom line  it is using `select` rather than `poll`:
![image](https://user-images.githubusercontent.com/16517192/53081331-4b89b200-3503-11e9-8271-3d7da85ac929.png)

I can replicate this on a different env if you'll say it's necessary (It'll take some time, and I won't touch the production server obviously).

**Comment by andymccurdy** [comment] 2019-02-20 10:03
It's in line with what I was skimming in the eventlet docs. So that means that in your environment redis-py is likely using `select.select` to validate the health of a connection.

`select.select` has a number of issues, most notably only being able to poll file descriptors with file numbers < ~1024. If you're running over that limit, the current implementation will simply return that the connection isn't ready, which would explain why you're seeing the error. See here: https://github.com/andymccurdy/redis-py/blob/master/redis/selector.py#L47

If you can correlate these errors around traffic spikes, that might further suggest that we're on the right track.

One thing you could try is to reduce the `max_connections` in the pool. Fewer connections means fewer file descriptors which should reduce the chance of hitting the `select.select` issue.

We could also make the selector more pluggable such that you could inject your own logic or turn off the health checks for your environment.

You could actually do this now with a (albeit ugly) monkey patch like so:

```python
from redis.selector import SelectSelector

class MySelector(SelectSelector):
    def check_is_ready_for_command(self, timeout):
        return True


from redis import connection
connection.DefaultSelector = MySelector
```

Or another possible solution is a simple flag to the connection pool to turn of the health checks. Enabling such a flag would cause the pool to behave the same as it did in 3.1.0.

**Comment by NirBenor** [comment] 2019-02-20 11:42
That makes a lot of sense, the server is also using lots of sockets for other tasks (other than connecting to redis) - and has the file descriptor limit (`ulimit -n`) set to a higher value than the default. So lowering `max_connections` won't do the trick.

Enabling such a flag would solve this (for now I tested this and the patch does work).
Thanks!

**Comment by gogglesguy** [comment] 2019-02-23 05:58
We were investigating a similar issue today in regards to using 3.2.0 and a monkey-patched select with eventlet. In our case, 3.2.0 solved many of the ConnectionError's caused by redis closing inactive connections, however, they didn't disappear completely and would still show on a regular basis.

We traced these latter errors down to a broken/incomplete eventlet select implementation.

As it turns out, in case a socket is both readable/writable state, select will randomly return either writable or readable, but never both at the same time (or exception for that matter).  You can see this in the following code from eventlet:

https://github.com/eventlet/eventlet/blob/a915bb642dd6cd4e92c959addff30509977a637c/eventlet/green/select.py#L51-L61

Each event handler will switch back to the original greenlet without knowing about any other events on the same file descriptor.

As a workaround, with limited testing, but so far no more errors, we found the following change to may do the job:

```
def check_is_ready_for_command(self, timeout):

    # first check read with no timeout
    r, _, e = select.select([self.sock],[],[self.sock], 0)
    if r or e:
        return False

    r, w, e = select.select([self.sock], [self.sock], [self.sock],
                            timeout)

    return bool(w and not r and not e)
```

**Comment by andymccurdy** [comment] 2019-02-23 06:52
@gogglesguy Thanks for digging into this. This is incredibly helpful.

My current thought is that we should make an `EventletSelector` implementation based on your patch above. Is there a canonical way to know that eventlet has patched a module in the current interpreter process? If so, we could modify `DefaultSelector` (https://github.com/andymccurdy/redis-py/blob/master/redis/selector.py#L186) to look for the presence of eventlet and return the `EventletSelector`.

**Comment by gogglesguy** [comment] 2019-02-23 16:59
Perhaps something like this:
https://github.com/ask/kombu/blob/master/kombu/syn.py

**Comment by gogglesguy** [comment] 2019-02-25 22:27
Although the workaround worked fine on our servers, the unit test (test_selector) still randomly failed (1 out of 10). I came up with a slight variation that I'm testing now which doesn't fail the unit tests. Will send a pull request.

**Comment by gogglesguy** [comment] 2019-02-26 16:31
Related eventlet issue and fix to select: https://github.com/eventlet/eventlet/issues/551
Not sure how actively maintained eventlet is these days..

**Comment by gogglesguy** [comment] 2019-02-28 19:57
And as we have been testing the eventlet patch the last couple of days, it is clear to me that we should keep redis-py as is, and fix the issue in eventlet.

**Comment by schlitzered** [comment] 2019-05-25 13:09
why not simply drop the usage of select at all, and simple use socket.settimeout() on the socket? this will do the same thing. the usage of the select module, in blocking code is, is more or less pointles. it is meant for async code, and handling multiple sockets at once...

using socket.settimeout(), will raise an exception after the specified timeout. this archives the same thing as using the select module, but in a cleaner way.

using socket.settimeout will also allow the removal of some clunky code around the socket handling, and you will not need to take care of other async frameworks that monkey patch core libraries.

**Comment by andymccurdy** [comment] 2019-05-25 19:01
@schlitzered I was under the impression that there are specific scenarios where a connection can be broken or stalled and reading from the connection blocks until the socket timeout is hit.

If this is true and we only rely on `socket.settimeout()` to control the blocking interval, we would never hit our global `socket_timeout` to indicate that the connection is having an issue. You would see this in the pubsub listen loop and possibly other places.

I can't recall a specific scenario that produces this behavior but I seem to remember it coming up at some point years ago. If I'm wrong, then your suggestion may very well work.

**Comment by schlitzered** [comment] 2019-05-27 06:14
i am not aware of such a scenario. if you use socket.settimeout(), it is guaranteed that a socket.timeout exception is raised after the specified timeout.

**Comment by andymccurdy** [comment] 2019-06-01 23:53
@NirBenor @gogglesguy @schlitzered 

I've put together a patch that uses nonblocking sockets to test the health of connections This completely removes the usage of selectors. If you guys could help test before I merge this patch I'd really appreciate it!

https://github.com/andymccurdy/redis-py/tree/nonblocking

**Comment by NirBenor** [comment] 2019-06-02 14:11
Sure, I'll update here in a few days.

**Comment by NirBenor** [comment] 2019-06-06 10:37
Appears to work fine 👍

**Comment by andymccurdy** [comment] 2019-06-06 17:52
Great, thanks for testing @NirBenor. I'll get this merged in a few days.

**Comment by dralley** [comment] 2020-01-06 14:55
Is this issue fixed then?

**Comment by andymccurdy** [comment] 2020-01-06 18:46
I believe this to be fixed. Please open a new issue if anyone continues to see this behavior.

**Closed by andymccurdy** 2020-01-06 18:46 UTC
