### ISSUE TITLE
Module instantiation doesn't return connection status

### ISSUE THREAD

**Issue by BeeShall** [andymccurdy/redis-py#1333] opened 2020-04-26 11:58 UTC
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?
Latest as of 4/26/20

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Pyhton 3.7

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

When you instantiate a Redis instance within r= Redis(), you do not get any indication that the server was connected or not. I have to manually run redis.echo() to throw an exception.

**Comment by andymccurdy** [comment] 2020-04-26 15:36
This is by design. redis-py connections are created and established only when they are needed.

**Comment by BeeShall** [comment] 2020-04-26 17:26
How do I check if the connection was successful?

**Comment by andymccurdy** [comment] 2020-04-26 18:03
If you really want to do that, then issue a command like you're already doing. Just remember that a TCP connection can fail at any time for various reasons outside of redis-py's control. Just because the connection is working well for your first command doesn't mean that the next command you try will succeed. A network device could have severed the link, the server could have gone away, etc etc.

**Comment by andymccurdy** [comment] 2020-04-27 22:46
Closing this as I don't believe this to be a problem. If you disagree, feel free to reopen.

**Closed by andymccurdy** 2020-04-27 22:46 UTC
