### ISSUE TITLE
Can we use georadius | georadiusbymember | geopos | geodist | geoadd command?

### ISSUE THREAD

**Issue by uname-yang** [andymccurdy/redis-py#746] opened 2016-05-30 06:53 UTC
Redis 3.2 release GEO function. how to use the new function in this deriver.

Thanks

**Comment by pfreixes** [comment] 2016-06-02 08:10
There is a PR [1] pending to be reviewed that implements all of these commands, I hope news soonner than later. Keeping on eye on that


[1] https://github.com/andymccurdy/redis-py/pull/736

**Comment by carltongibson** [comment] 2016-06-02 08:27
Duplicate of #636

**Comment by uname-yang** [comment] 2016-06-06 04:59
Thanks

**Comment by daTokenizer** [comment] 2016-06-24 12:15
GEOADD/GEORADIUS both work pretty well for me

**Comment by andymccurdy** [comment] 2016-06-24 13:29
#736 was merged. closing this.

**Closed by andymccurdy** 2016-06-24 13:29 UTC
