### ISSUE TITLE
zadd raises TypeError exception

### ISSUE THREAD

**Issue by nitingupta89** [andymccurdy/redis-py#954] opened 2018-02-15 07:54 UTC
When i try 
to update score of non-existing field like this:
`r.zadd('fooset', 'xx', 'INCR', 10, 'bar')`
OR 
to update score of existing field like this:
`r.zadd('fooset', 'xx', 'INCR', 10, 'zoo')`

ZADD returns None and method is raising
`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by Chronial** [comment] 2018-04-24 13:25
This is a duplicate of https://github.com/andymccurdy/redis-py/issues/649

**Closed** 2018-11-15 04:29 UTC

**Comment by andymccurdy** [comment] 2018-11-15 04:31
Fixed in redis-py 3.0
