### ISSUE TITLE
Inoperable with numpy >= 14.x

### ISSUE THREAD

**Issue by ericandrewmeadows** [andymccurdy/redis-py#1074] opened 2018-11-16 13:48 UTC
The following error is now ever-present when using this Redis release:

<img width="793" alt="screen shot 2018-11-15 at 7 01 06 pm" src="https://user-images.githubusercontent.com/19596182/48625124-481ee180-e97c-11e8-9ed6-5e4ec72e01bc.png">

This issue was not present on redis==2.10.6.

For reference, I am using `numpy==1.15.4`, which is required for pyarrow.

**Comment by jdufresne** [comment] 2018-11-16 15:04
This is not a bug in redis-py, but in django-redis. The issue is being tracked in niwinz/django-redis#342.

**Comment by itamarhaber** [comment] 2018-11-17 13:13
Also reported in #1071 - closing.

**Closed by itamarhaber** 2018-11-17 13:13 UTC
