### ISSUE TITLE
Why there is no monitoring method

### ISSUE THREAD

**Issue by githublaohu** [andymccurdy/redis-py#805] opened 2016-12-03 03:45 UTC
Want to pass monitoring statistics related information。

Found that redis-py did not have this method

**Comment by MrKiven** [comment] 2016-12-03 03:51
how about `redis_client.info()` ?

**Comment by githublaohu** [comment] 2016-12-03 03:54
Info( ) statistics are not comprehensive, monitoring need to provide more detailed information to monitor the use of redis

chinaese? 
用汉语交流可以好。

**Comment by miketheman** [comment] 2016-12-14 02:45
What other statistics would you expect to see beyond what redis info returns?

**Comment by githublaohu** [comment] 2016-12-14 02:51
Such as read/write ratio, hot spot data

**Comment by miketheman** [comment] 2016-12-14 05:10
I don't think either of these is something that the redis database would provide, and would be curious to know if the maintainer(s) would be interested in calculated values for read/write ratio from some sort of  extended info command.

I doubt "hot spot" would ever be included in this library, as it would require some state to be stored to determine this.

**Comment by AngusP** [comment] 2017-01-24 01:01
This was PR'd ages ago in #194, would now need review before it could be merged as things have changed and there's a conflict

**Comment by gyermolenko** [comment] 2019-06-08 09:52
Aforementioned PR was merged, so the issue is outdated now

**Closed** 2019-06-08 11:22 UTC
