### ISSUE TITLE
zadd inconsistent in accepting arguments

### ISSUE THREAD

**Issue by yuyilei** [andymccurdy/redis-py#1020] opened 2018-08-20 03:18 UTC
zadd(name, *args, **kwargs) accepts arguments in two ways: 
- As *args, in the form of: score, name, … 
- As **kwargs, in the form of: name=score, …

I pass my parameter in front ways, replacing the `name` with a variable，but there  is something inconsistent: 

```python 
>>> import redis 
>>> r = redis.StrictRedis()
>>> key = "value" 
>>> r.zadd("test",key=3) 
1
>>> r.zrange("test",0,-1,withscores=True)
[(b'key', 3.0)]
>>>  r.zadd("test",3,key) 
1
>>> r.zrange("test",0,-1,withscores=True)
[(b'key', 3.0), (b'value', 3.0)]
```

Why  the `**kwargs` way can not pass real variable?  Why the two ways lead to different results?
And it pass the formal parameter in a function: 
```python 
>>> def f(r,argkey):
>>>       r.zadd("test2",argkey=2) 
>>>
>>> key2 = "value2" 
>>> f(r,key2) 
>>> r.zrange("test2",0,-1,withscores=True)
>>> [(b'argkey', 2.0)]
```

**Comment by ifiok** [comment] 2018-08-31 23:17
@yuyilei I don't see what the issue is.

For the first case;
`r.zadd("test",key=3)`
The result is:
 ```
>>> r.zrange("test",0,-1,withscores=True)
[(b'key', 3.0)]
```
which is the expected behavior.

For the second case, since you are using *args, you have already set the value of **key** to **value**, hence Python will resolve the value:
`>>>  r.zadd("test",3,key),`
Here key actually represents value because of` >>> key = "value"` 

So:

```
 >>> r.zrange("test",0,-1,withscores=True)
[(b'key', 3.0), (b'value', 3.0)]
```

is actually the expected behavior.

**Comment by itamarhaber** [comment] 2018-11-03 12:38
@Hello @yuyilei 

I agree with @ifiok in that there is no issue here apparently.

Closing this - feel free to reopen if needed.

**Closed by itamarhaber** 2018-11-03 12:38 UTC
