### ISSUE TITLE
Bug related to argument check in redis.hset()

### ISSUE THREAD

**Issue by jroose-pp** [andymccurdy/redis-py#1340] opened 2020-05-08 20:02 UTC
**Version**: 
Latest git master:  https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L3041

**Platform**: 
Python 3.8.1 on Amazon Linux

**Description**: 
Based on redis-py's type checking int(x) should be a valid key for hset().  However, if hset is passed `redis.hset(myhash, key=0, value="mystr")` then the Error: `redis.exceptions.DataError: 'hset' with no key value pairs` because inputs are improperly sanitized.  Using `redis.hset(myhash, mapping={0: "mystr"})` works as a workaround, but this cornercase could cause hard to debug errors when 0 is passed as a hash key.  

I suggest changing the current check: 
```if not key and not mapping:```
to 
```if (key is None) and not mapping:```

**Comment by jroose-pp** [comment] 2020-05-08 20:27
I just realized that a similar bug is present on line 3044 as well:
```
        if key:
            items.extend((key, value))
```

Which needs to change to:
```
        if key is not None:
            items.extend((key, value))
```

**Comment by andymccurdy** [comment] 2020-05-08 20:47
This is a duplicate of #1337. I'm going to close this issue and keep the conversation over there. If you want to submit a PR that would be great.

**Closed by andymccurdy** 2020-05-08 20:47 UTC
