### ISSUE TITLE
3.4.0 breaks connecting with connection URL

### ISSUE THREAD

**Issue by jbasko** [andymccurdy/redis-py#1278] opened 2020-02-01 01:16 UTC
**Version**: 3.4.0

**Platform**: Python 3.7.5, OS X and Linux

**Description**: 
This code:

```
import os

import redis

r = redis.StrictRedis.from_url(os.environ["REDIS_URL"])
print("set key1 123")
print(r.set('key1', '123'))
print("get key1")
print(r.get('key1'))
```

raises:

```
set key1 123
Traceback (most recent call last):
  File "scripts/test_redis.py", line 8, in <module>
    print(r.set('key1', '123'))
  File "~/.pyenv/versions/skdb/lib/python3.7/site-packages/redis/client.py", line 1772, in set
    return self.execute_command('SET', *pieces)
  File "~/.pyenv/versions/skdb/lib/python3.7/site-packages/redis/client.py", line 881, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "~/.pyenv/versions/skdb/lib/python3.7/site-packages/redis/connection.py", line 1178, in get_connection
    connection.connect()
  File "~/.pyenv/versions/skdb/lib/python3.7/site-packages/redis/connection.py", line 559, in connect
    self.on_connect()
  File "~/.pyenv/versions/skdb/lib/python3.7/site-packages/redis/connection.py", line 633, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "~/.pyenv/versions/skdb/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'auth' command
```

The connection URL is like the ones used on Heroku:
`redis://h:blablabla@ec2-11-11-11-1.eu-west-1.compute.amazonaws.com:12345`

Doesn't happen with 3.3.11

**Comment by zyv** [comment] 2020-02-01 11:10
This is a duplicate of #1274.

**Closed** 2020-02-01 12:23 UTC
